_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 35
                - 55
                - 105
            "2":
                - 1
                - 35
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.1
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
